import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

# Generated by Django 5.2.13 on 2026-05-18 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0001_initial"),
    ]


operations = [
    migrations.CreateModel(
        name="Profile",
        fields=[
            (
                "id",
                models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name="ID",
                ),
            ),
            (
                "role",
                models.CharField(
                    choices=[("vendor", "Vendor"), ("buyer", "Buyer")],
                    max_length=10,
                ),
            ),
            (
                "user",
                models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    to=settings.AUTH_USER_MODEL,
                ),
            ),
        ],
    ),
]
