# Generated by Django 5.2.13 on 2026-05-19 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_create_missing_orderitem_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="verified",
            field=models.BooleanField(default=False),
        ),
    ]
