# Generated by Django 5.2.13 on 2026-05-25 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_add_verified_to_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.PositiveIntegerField(),
        ),
    ]
